Repository DALPy-Developers/DALPy, pull requests merged in 2022-03, with the labels that each got.

#10 Bugfix to copy_stack
  src/cormen_lib/factory_utils.py
  tests/factory_utils_test.py
Labels: bug

#16 added new Set __init__; replaced Set:add with Set:union; added HashTa…
  docs/hashing.html
  docs/sets.html
  setup.cfg
  src/dalpy/hashing.py
  src/dalpy/sets.py
  tests/hashing_tests.py
  tests/sets_test.py
Labels: enhancement

#23 Fixed PriorityQueue Runtimes + other adjustments
  docs/arrays.html
  docs/graphs.html
  docs/hashing.html
  docs/heaps.html
  docs/sets.html
  docs/trees.html
  src/dalpy/arrays.py
  src/dalpy/graphs.py
  src/dalpy/hashing.py
  src/dalpy/heaps.py
  src/dalpy/sets.py
  src/dalpy/trees.py
  tests/heaps_test.py
Labels: documentation
